// AUTO-GENERATED by scripts/build-pricing-snapshot.ts — do not edit by hand.
// Offline pricing fallback: Anthropic models only, sourced from LiteLLM.
import type { PricingTable } from '../types/Pricing.js';

export const EMBEDDED_PRICING: PricingTable = {
  "anthropic.claude-3-5-haiku-20241022-v1:0": {
    "input": 8e-7,
    "output": 0.000004,
    "cacheCreate": 0.000001,
    "cacheRead": 8e-8
  },
  "anthropic.claude-haiku-4-5-20251001-v1:0": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.00000125,
    "cacheRead": 1e-7
  },
  "anthropic.claude-haiku-4-5@20251001": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.00000125,
    "cacheRead": 1e-7
  },
  "anthropic.claude-3-5-sonnet-20240620-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.00003,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "anthropic.claude-3-5-sonnet-20241022-v2:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.00003,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "anthropic.claude-3-7-sonnet-20240620-v1:0": {
    "input": 0.0000036,
    "output": 0.000018,
    "cacheCreate": 0.0000045,
    "cacheRead": 3.6e-7
  },
  "anthropic.claude-3-7-sonnet-20250219-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "anthropic.claude-3-haiku-20240307-v1:0": {
    "input": 2.5e-7,
    "output": 0.00000125,
    "cacheCreate": 3.125e-7,
    "cacheRead": 2.5e-8
  },
  "anthropic.claude-3-opus-20240229-v1:0": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "anthropic.claude-3-sonnet-20240229-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "anthropic.claude-instant-v1": {
    "input": 8e-7,
    "output": 0.0000024,
    "cacheCreate": 0.000001,
    "cacheRead": 8e-8
  },
  "anthropic.claude-opus-4-1-20250805-v1:0": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "anthropic.claude-opus-4-20250514-v1:0": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "anthropic.claude-opus-4-5-20251101-v1:0": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "anthropic.claude-opus-4-6-v1": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "global.anthropic.claude-opus-4-6-v1": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "us.anthropic.claude-opus-4-6-v1": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "eu.anthropic.claude-opus-4-6-v1": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "au.anthropic.claude-opus-4-6-v1": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "anthropic.claude-opus-4-7": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "anthropic.claude-mythos-preview": {
    "input": 0,
    "output": 0,
    "cacheCreate": 0,
    "cacheRead": 0
  },
  "global.anthropic.claude-opus-4-7": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "us.anthropic.claude-opus-4-7": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "eu.anthropic.claude-opus-4-7": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "au.anthropic.claude-opus-4-7": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "anthropic.claude-fable-5": {
    "input": 0.00001,
    "output": 0.00005,
    "cacheCreate": 0.0000125,
    "cacheRead": 0.000001
  },
  "global.anthropic.claude-fable-5": {
    "input": 0.00001,
    "output": 0.00005,
    "cacheCreate": 0.0000125,
    "cacheRead": 0.000001
  },
  "us.anthropic.claude-fable-5": {
    "input": 0.000011,
    "output": 0.000055,
    "cacheCreate": 0.00001375,
    "cacheRead": 0.0000011
  },
  "eu.anthropic.claude-fable-5": {
    "input": 0.000011,
    "output": 0.000055,
    "cacheCreate": 0.00001375,
    "cacheRead": 0.0000011
  },
  "anthropic.claude-opus-5": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "global.anthropic.claude-opus-5": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "us.anthropic.claude-opus-5": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "eu.anthropic.claude-opus-5": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "au.anthropic.claude-opus-5": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "jp.anthropic.claude-opus-5": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "anthropic.claude-opus-4-8": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "global.anthropic.claude-opus-4-8": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "us.anthropic.claude-opus-4-8": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "eu.anthropic.claude-opus-4-8": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "au.anthropic.claude-opus-4-8": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "jp.anthropic.claude-opus-4-8": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "jp.anthropic.claude-opus-4-7": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "anthropic.claude-sonnet-5": {
    "input": 0.000002,
    "output": 0.00001,
    "cacheCreate": 0.0000025,
    "cacheRead": 2e-7
  },
  "global.anthropic.claude-sonnet-5": {
    "input": 0.000002,
    "output": 0.00001,
    "cacheCreate": 0.0000025,
    "cacheRead": 2e-7
  },
  "us.anthropic.claude-sonnet-5": {
    "input": 0.0000022,
    "output": 0.000011,
    "cacheCreate": 0.00000275,
    "cacheRead": 2.2e-7
  },
  "eu.anthropic.claude-sonnet-5": {
    "input": 0.0000022,
    "output": 0.000011,
    "cacheCreate": 0.00000275,
    "cacheRead": 2.2e-7
  },
  "au.anthropic.claude-sonnet-5": {
    "input": 0.0000022,
    "output": 0.000011,
    "cacheCreate": 0.00000275,
    "cacheRead": 2.2e-7
  },
  "jp.anthropic.claude-sonnet-5": {
    "input": 0.0000022,
    "output": 0.000011,
    "cacheCreate": 0.00000275,
    "cacheRead": 2.2e-7
  },
  "anthropic.claude-sonnet-4-6": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "global.anthropic.claude-sonnet-4-6": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "us.anthropic.claude-sonnet-4-6": {
    "input": 0.0000033,
    "output": 0.0000165,
    "cacheCreate": 0.000004125,
    "cacheRead": 3.3e-7
  },
  "eu.anthropic.claude-sonnet-4-6": {
    "input": 0.0000033,
    "output": 0.0000165,
    "cacheCreate": 0.000004125,
    "cacheRead": 3.3e-7
  },
  "au.anthropic.claude-sonnet-4-6": {
    "input": 0.0000033,
    "output": 0.0000165,
    "cacheCreate": 0.000004125,
    "cacheRead": 3.3e-7
  },
  "jp.anthropic.claude-sonnet-4-6": {
    "input": 0.0000033,
    "output": 0.0000165,
    "cacheCreate": 0.000004125,
    "cacheRead": 3.3e-7
  },
  "anthropic.claude-sonnet-4-20250514-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "anthropic.claude-sonnet-4-5-20250929-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "anthropic.claude-v1": {
    "input": 0.000008,
    "output": 0.000024,
    "cacheCreate": 0.000009999999999999999,
    "cacheRead": 8e-7
  },
  "anthropic.claude-v2:1": {
    "input": 0.000008,
    "output": 0.000024,
    "cacheCreate": 0.000009999999999999999,
    "cacheRead": 8e-7
  },
  "apac.anthropic.claude-3-5-sonnet-20240620-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "apac.anthropic.claude-3-5-sonnet-20241022-v2:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "apac.anthropic.claude-3-haiku-20240307-v1:0": {
    "input": 2.5e-7,
    "output": 0.00000125,
    "cacheCreate": 3.125e-7,
    "cacheRead": 2.5e-8
  },
  "apac.anthropic.claude-haiku-4-5-20251001-v1:0": {
    "input": 0.0000011,
    "output": 0.0000055,
    "cacheCreate": 0.000001375,
    "cacheRead": 1.1e-7
  },
  "apac.anthropic.claude-3-sonnet-20240229-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "apac.anthropic.claude-sonnet-4-20250514-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "au.anthropic.claude-sonnet-4-5-20250929-v1:0": {
    "input": 0.0000033,
    "output": 0.0000165,
    "cacheCreate": 0.000004125,
    "cacheRead": 3.3e-7,
    "inputAbove200k": 0.0000066,
    "outputAbove200k": 0.00002475,
    "cacheCreateAbove200k": 0.00000825,
    "cacheReadAbove200k": 6.6e-7
  },
  "azure_ai/claude-haiku-4-5": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.00000125,
    "cacheRead": 1e-7
  },
  "azure_ai/claude-opus-4-5": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "azure_ai/claude-opus-4-6": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "azure_ai/claude-opus-4-7": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "azure_ai/claude-fable-5": {
    "input": 0.00001,
    "output": 0.00005,
    "cacheCreate": 0.0000125,
    "cacheRead": 0.000001
  },
  "azure_ai/claude-opus-5": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "azure_ai/claude-opus-4-8": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "azure_ai/claude-opus-4-1": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "azure_ai/claude-sonnet-4-5": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "azure_ai/claude-sonnet-5": {
    "input": 0.000002,
    "output": 0.00001,
    "cacheCreate": 0.0000025,
    "cacheRead": 2e-7
  },
  "azure_ai/claude-sonnet-4-6": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "bedrock/ap-northeast-1/anthropic.claude-instant-v1": {
    "input": 0.00000223,
    "output": 0.00000755,
    "cacheCreate": 0.0000027875,
    "cacheRead": 2.23e-7
  },
  "bedrock/ap-northeast-1/anthropic.claude-v1": {
    "input": 0.000008,
    "output": 0.000024,
    "cacheCreate": 0.000009999999999999999,
    "cacheRead": 8e-7
  },
  "bedrock/ap-northeast-1/anthropic.claude-v2:1": {
    "input": 0.000008,
    "output": 0.000024,
    "cacheCreate": 0.000009999999999999999,
    "cacheRead": 8e-7
  },
  "bedrock/eu-central-1/anthropic.claude-instant-v1": {
    "input": 0.00000248,
    "output": 0.00000838,
    "cacheCreate": 0.0000031,
    "cacheRead": 2.48e-7
  },
  "bedrock/eu-central-1/anthropic.claude-v1": {
    "input": 0.000008,
    "output": 0.000024,
    "cacheCreate": 0.000009999999999999999,
    "cacheRead": 8e-7
  },
  "bedrock/eu-central-1/anthropic.claude-v2:1": {
    "input": 0.000008,
    "output": 0.000024,
    "cacheCreate": 0.000009999999999999999,
    "cacheRead": 8e-7
  },
  "bedrock/invoke/anthropic.claude-3-5-sonnet-20240620-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "bedrock/us-east-1/anthropic.claude-instant-v1": {
    "input": 8e-7,
    "output": 0.0000024,
    "cacheCreate": 0.000001,
    "cacheRead": 8e-8
  },
  "bedrock/us-east-1/anthropic.claude-v1": {
    "input": 0.000008,
    "output": 0.000024,
    "cacheCreate": 0.000009999999999999999,
    "cacheRead": 8e-7
  },
  "bedrock/us-east-1/anthropic.claude-v2:1": {
    "input": 0.000008,
    "output": 0.000024,
    "cacheCreate": 0.000009999999999999999,
    "cacheRead": 8e-7
  },
  "bedrock/us-gov-east-1/anthropic.claude-3-5-sonnet-20240620-v1:0": {
    "input": 0.0000036,
    "output": 0.000018,
    "cacheCreate": 0.0000045,
    "cacheRead": 3.6e-7
  },
  "bedrock/us-gov-east-1/anthropic.claude-3-haiku-20240307-v1:0": {
    "input": 3e-7,
    "output": 0.0000015,
    "cacheCreate": 3.75e-7,
    "cacheRead": 3e-8
  },
  "bedrock/us-gov-east-1/anthropic.claude-sonnet-4-5-20250929-v1:0": {
    "input": 0.0000036,
    "output": 0.000018,
    "cacheCreate": 0.0000045,
    "cacheRead": 3.6e-7
  },
  "bedrock/us-gov-east-1/claude-sonnet-4-5-20250929-v1:0": {
    "input": 0.0000036,
    "output": 0.000018,
    "cacheCreate": 0.0000045,
    "cacheRead": 3.6e-7
  },
  "bedrock/us-gov-west-1/anthropic.claude-3-7-sonnet-20250219-v1:0": {
    "input": 0.0000036,
    "output": 0.000018,
    "cacheCreate": 0.0000045,
    "cacheRead": 3.6e-7
  },
  "bedrock/us-gov-west-1/anthropic.claude-3-5-sonnet-20240620-v1:0": {
    "input": 0.0000036,
    "output": 0.000018,
    "cacheCreate": 0.0000045,
    "cacheRead": 3.6e-7
  },
  "bedrock/us-gov-west-1/anthropic.claude-3-haiku-20240307-v1:0": {
    "input": 3e-7,
    "output": 0.0000015,
    "cacheCreate": 3.75e-7,
    "cacheRead": 3e-8
  },
  "bedrock/us-gov-west-1/anthropic.claude-sonnet-4-5-20250929-v1:0": {
    "input": 0.0000036,
    "output": 0.000018,
    "cacheCreate": 0.0000045,
    "cacheRead": 3.6e-7
  },
  "bedrock/us-gov-west-1/claude-sonnet-4-5-20250929-v1:0": {
    "input": 0.0000036,
    "output": 0.000018,
    "cacheCreate": 0.0000045,
    "cacheRead": 3.6e-7
  },
  "bedrock/us-west-2/anthropic.claude-instant-v1": {
    "input": 8e-7,
    "output": 0.0000024,
    "cacheCreate": 0.000001,
    "cacheRead": 8e-8
  },
  "bedrock/us-west-2/anthropic.claude-v1": {
    "input": 0.000008,
    "output": 0.000024,
    "cacheCreate": 0.000009999999999999999,
    "cacheRead": 8e-7
  },
  "bedrock/us-west-2/anthropic.claude-v2:1": {
    "input": 0.000008,
    "output": 0.000024,
    "cacheCreate": 0.000009999999999999999,
    "cacheRead": 8e-7
  },
  "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0": {
    "input": 8e-7,
    "output": 0.000004,
    "cacheCreate": 0.000001,
    "cacheRead": 8e-8
  },
  "claude-haiku-4-5-20251001": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.00000125,
    "cacheRead": 1e-7
  },
  "claude-haiku-4-5": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.00000125,
    "cacheRead": 1e-7
  },
  "claude-3-7-sonnet-20250219": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "claude-3-haiku-20240307": {
    "input": 2.5e-7,
    "output": 0.00000125,
    "cacheCreate": 3e-7,
    "cacheRead": 3e-8
  },
  "claude-3-opus-20240229": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "claude-4-opus-20250514": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "claude-4-sonnet-20250514": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "claude-sonnet-4-5": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "claude-sonnet-4-5-20250929": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "claude-sonnet-5": {
    "input": 0.000002,
    "output": 0.00001,
    "cacheCreate": 0.0000025,
    "cacheRead": 2e-7
  },
  "claude-sonnet-4-6": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "claude-sonnet-4-5-20250929-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "claude-opus-4-1": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "claude-opus-4-1-20250805": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "claude-opus-4-20250514": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "claude-opus-4-5-20251101": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "claude-opus-4-5": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "claude-opus-4-6": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "claude-opus-4-6-20260205": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "claude-opus-4-7": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "claude-opus-4-7-20260416": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "claude-fable-5": {
    "input": 0.00001,
    "output": 0.00005,
    "cacheCreate": 0.0000125,
    "cacheRead": 0.000001
  },
  "claude-opus-5": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "claude-opus-4-8": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "claude-sonnet-4-20250514": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "databricks/databricks-claude-3-7-sonnet": {
    "input": 0.0000029999900000000002,
    "output": 0.000015000020000000002,
    "cacheCreate": 0.0000037499875000000005,
    "cacheRead": 2.9999900000000006e-7
  },
  "databricks/databricks-claude-haiku-4-5": {
    "input": 0.00000100002,
    "output": 0.00000500003,
    "cacheCreate": 0.0000012500250000000002,
    "cacheRead": 1.0000200000000001e-7
  },
  "databricks/databricks-claude-opus-4": {
    "input": 0.000015000020000000002,
    "output": 0.00007500003000000001,
    "cacheCreate": 0.000018750025000000003,
    "cacheRead": 0.0000015000020000000003
  },
  "databricks/databricks-claude-opus-4-1": {
    "input": 0.000015000020000000002,
    "output": 0.00007500003000000001,
    "cacheCreate": 0.000018750025000000003,
    "cacheRead": 0.0000015000020000000003
  },
  "databricks/databricks-claude-opus-4-5": {
    "input": 0.00000500003,
    "output": 0.000025000010000000002,
    "cacheCreate": 0.0000062500375,
    "cacheRead": 5.000030000000001e-7
  },
  "databricks/databricks-claude-opus-4-6": {
    "input": 0.00000500003,
    "output": 0.000025000010000000002,
    "cacheCreate": 0.0000062500375,
    "cacheRead": 5.000030000000001e-7
  },
  "databricks/databricks-claude-sonnet-4": {
    "input": 0.0000029999900000000002,
    "output": 0.000015000020000000002,
    "cacheCreate": 0.0000037499875000000005,
    "cacheRead": 2.9999900000000006e-7
  },
  "databricks/databricks-claude-sonnet-4-1": {
    "input": 0.0000029999900000000002,
    "output": 0.000015000020000000002,
    "cacheCreate": 0.0000037499875000000005,
    "cacheRead": 2.9999900000000006e-7
  },
  "databricks/databricks-claude-sonnet-4-5": {
    "input": 0.0000029999900000000002,
    "output": 0.000015000020000000002,
    "cacheCreate": 0.0000037499875000000005,
    "cacheRead": 2.9999900000000006e-7
  },
  "databricks/databricks-claude-sonnet-4-6": {
    "input": 0.0000029999900000000002,
    "output": 0.000015000020000000002,
    "cacheCreate": 0.0000037499875000000005,
    "cacheRead": 2.9999900000000006e-7
  },
  "deepinfra/anthropic/claude-3-7-sonnet-latest": {
    "input": 0.0000033,
    "output": 0.0000165,
    "cacheCreate": 0.000004125,
    "cacheRead": 3.3e-7
  },
  "deepinfra/anthropic/claude-4-opus": {
    "input": 0.0000165,
    "output": 0.0000825,
    "cacheCreate": 0.000020625,
    "cacheRead": 0.0000016500000000000003
  },
  "deepinfra/anthropic/claude-4-sonnet": {
    "input": 0.0000033,
    "output": 0.0000165,
    "cacheCreate": 0.000004125,
    "cacheRead": 3.3e-7
  },
  "eu.anthropic.claude-3-5-haiku-20241022-v1:0": {
    "input": 2.5e-7,
    "output": 0.00000125,
    "cacheCreate": 3.125e-7,
    "cacheRead": 2.5e-8
  },
  "eu.anthropic.claude-haiku-4-5-20251001-v1:0": {
    "input": 0.0000011,
    "output": 0.0000055,
    "cacheCreate": 0.000001375,
    "cacheRead": 1.1e-7
  },
  "eu.anthropic.claude-3-5-sonnet-20240620-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "eu.anthropic.claude-3-5-sonnet-20241022-v2:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "eu.anthropic.claude-3-7-sonnet-20250219-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "eu.anthropic.claude-3-haiku-20240307-v1:0": {
    "input": 2.5e-7,
    "output": 0.00000125,
    "cacheCreate": 3.125e-7,
    "cacheRead": 2.5e-8
  },
  "eu.anthropic.claude-3-opus-20240229-v1:0": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "eu.anthropic.claude-3-sonnet-20240229-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "eu.anthropic.claude-opus-4-1-20250805-v1:0": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "eu.anthropic.claude-opus-4-20250514-v1:0": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "eu.anthropic.claude-sonnet-4-20250514-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "eu.anthropic.claude-sonnet-4-5-20250929-v1:0": {
    "input": 0.0000033,
    "output": 0.0000165,
    "cacheCreate": 0.000004125,
    "cacheRead": 3.3e-7,
    "inputAbove200k": 0.0000066,
    "outputAbove200k": 0.00002475,
    "cacheCreateAbove200k": 0.00000825,
    "cacheReadAbove200k": 6.6e-7
  },
  "gmi/anthropic/claude-opus-4.5": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5.000000000000001e-7
  },
  "gmi/anthropic/claude-sonnet-4.5": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3.0000000000000004e-7
  },
  "gmi/anthropic/claude-sonnet-4": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3.0000000000000004e-7
  },
  "gmi/anthropic/claude-opus-4": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.000018750000000000002,
    "cacheRead": 0.0000015
  },
  "global.anthropic.claude-sonnet-4-5-20250929-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "global.anthropic.claude-sonnet-4-20250514-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "global.anthropic.claude-haiku-4-5-20251001-v1:0": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.00000125,
    "cacheRead": 1e-7
  },
  "gradient_ai/anthropic-claude-3-opus": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.000018750000000000002,
    "cacheRead": 0.0000015
  },
  "gradient_ai/anthropic-claude-3.5-haiku": {
    "input": 8e-7,
    "output": 0.000004,
    "cacheCreate": 0.000001,
    "cacheRead": 8e-8
  },
  "gradient_ai/anthropic-claude-3.5-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3.0000000000000004e-7
  },
  "gradient_ai/anthropic-claude-3.7-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3.0000000000000004e-7
  },
  "jp.anthropic.claude-sonnet-4-5-20250929-v1:0": {
    "input": 0.0000033,
    "output": 0.0000165,
    "cacheCreate": 0.000004125,
    "cacheRead": 3.3e-7,
    "inputAbove200k": 0.0000066,
    "outputAbove200k": 0.00002475,
    "cacheCreateAbove200k": 0.00000825,
    "cacheReadAbove200k": 6.6e-7
  },
  "jp.anthropic.claude-haiku-4-5-20251001-v1:0": {
    "input": 0.0000011,
    "output": 0.0000055,
    "cacheCreate": 0.000001375,
    "cacheRead": 1.1e-7
  },
  "openrouter/anthropic/claude-3-haiku": {
    "input": 2.5e-7,
    "output": 0.00000125,
    "cacheCreate": 3.1249999999999997e-7,
    "cacheRead": 2.5e-8
  },
  "openrouter/anthropic/claude-3.5-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3.0000000000000004e-7
  },
  "openrouter/anthropic/claude-3.7-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3.0000000000000004e-7
  },
  "openrouter/anthropic/claude-opus-4": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "openrouter/anthropic/claude-opus-4.1": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "openrouter/anthropic/claude-sonnet-4": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "openrouter/anthropic/claude-sonnet-4.6": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "openrouter/anthropic/claude-opus-4.5": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "openrouter/anthropic/claude-opus-4.6": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "openrouter/anthropic/claude-sonnet-4.5": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "openrouter/anthropic/claude-haiku-4.5": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.00000125,
    "cacheRead": 1e-7
  },
  "openrouter/anthropic/claude-opus-4.7": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "replicate/anthropic/claude-4.5-haiku": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.0000012499999999999999,
    "cacheRead": 1e-7
  },
  "replicate/anthropic/claude-4-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3.0000000000000004e-7
  },
  "replicate/anthropic/claude-3.7-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3.0000000000000004e-7
  },
  "replicate/anthropic/claude-3.5-haiku": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.0000012499999999999999,
    "cacheRead": 1e-7
  },
  "replicate/anthropic/claude-3.5-sonnet": {
    "input": 0.00000375,
    "output": 0.00001875,
    "cacheCreate": 0.0000046875000000000004,
    "cacheRead": 3.75e-7
  },
  "replicate/anthropic/claude-4.5-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3.0000000000000004e-7
  },
  "snowflake/claude-3-5-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "us.anthropic.claude-3-5-haiku-20241022-v1:0": {
    "input": 8e-7,
    "output": 0.000004,
    "cacheCreate": 0.000001,
    "cacheRead": 8e-8
  },
  "us.anthropic.claude-haiku-4-5-20251001-v1:0": {
    "input": 0.0000011,
    "output": 0.0000055,
    "cacheCreate": 0.000001375,
    "cacheRead": 1.1e-7
  },
  "us.anthropic.claude-3-5-sonnet-20240620-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "us.anthropic.claude-3-5-sonnet-20241022-v2:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "us.anthropic.claude-3-7-sonnet-20250219-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "us.anthropic.claude-3-haiku-20240307-v1:0": {
    "input": 2.5e-7,
    "output": 0.00000125,
    "cacheCreate": 3.125e-7,
    "cacheRead": 2.5e-8
  },
  "us.anthropic.claude-3-opus-20240229-v1:0": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "us.anthropic.claude-3-sonnet-20240229-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "us.anthropic.claude-opus-4-1-20250805-v1:0": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "us.anthropic.claude-sonnet-4-5-20250929-v1:0": {
    "input": 0.0000033,
    "output": 0.0000165,
    "cacheCreate": 0.000004125,
    "cacheRead": 3.3e-7,
    "inputAbove200k": 0.0000066,
    "outputAbove200k": 0.00002475,
    "cacheCreateAbove200k": 0.00000825,
    "cacheReadAbove200k": 6.6e-7
  },
  "us-gov.anthropic.claude-sonnet-4-5-20250929-v1:0": {
    "input": 0.0000036,
    "output": 0.000018,
    "cacheCreate": 0.0000045,
    "cacheRead": 3.6e-7,
    "inputAbove200k": 0.0000072,
    "outputAbove200k": 0.000027,
    "cacheCreateAbove200k": 0.000009,
    "cacheReadAbove200k": 7.2e-7
  },
  "au.anthropic.claude-haiku-4-5-20251001-v1:0": {
    "input": 0.0000011,
    "output": 0.0000055,
    "cacheCreate": 0.000001375,
    "cacheRead": 1.1e-7
  },
  "us.anthropic.claude-opus-4-20250514-v1:0": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "us.anthropic.claude-opus-4-5-20251101-v1:0": {
    "input": 0.0000055,
    "output": 0.0000275,
    "cacheCreate": 0.000006875,
    "cacheRead": 5.5e-7
  },
  "global.anthropic.claude-opus-4-5-20251101-v1:0": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "eu.anthropic.claude-opus-4-5-20251101-v1:0": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "us.anthropic.claude-sonnet-4-20250514-v1:0": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "vercel_ai_gateway/anthropic/claude-3-haiku": {
    "input": 2.5e-7,
    "output": 0.00000125,
    "cacheCreate": 3e-7,
    "cacheRead": 3e-8
  },
  "vercel_ai_gateway/anthropic/claude-3-opus": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "vercel_ai_gateway/anthropic/claude-3.5-haiku": {
    "input": 8e-7,
    "output": 0.000004,
    "cacheCreate": 0.000001,
    "cacheRead": 8e-8
  },
  "vercel_ai_gateway/anthropic/claude-3.5-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "vercel_ai_gateway/anthropic/claude-3.7-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "vercel_ai_gateway/anthropic/claude-4-opus": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "vercel_ai_gateway/anthropic/claude-4-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "vercel_ai_gateway/anthropic/claude-3-5-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "vercel_ai_gateway/anthropic/claude-3-5-sonnet-20241022": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "vercel_ai_gateway/anthropic/claude-3-7-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "vercel_ai_gateway/anthropic/claude-haiku-4.5": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.00000125,
    "cacheRead": 1e-7
  },
  "vercel_ai_gateway/anthropic/claude-opus-4": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "vercel_ai_gateway/anthropic/claude-opus-4.1": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "vercel_ai_gateway/anthropic/claude-opus-4.5": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "vercel_ai_gateway/anthropic/claude-opus-4.6": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "vercel_ai_gateway/anthropic/claude-sonnet-4": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "vercel_ai_gateway/anthropic/claude-sonnet-4.5": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "vertex_ai/claude-3-5-haiku": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.0000012499999999999999,
    "cacheRead": 1e-7
  },
  "vertex_ai/claude-3-5-haiku@20241022": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.0000012499999999999999,
    "cacheRead": 1e-7
  },
  "vertex_ai/claude-haiku-4-5": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.00000125,
    "cacheRead": 1e-7
  },
  "vertex_ai/claude-haiku-4-5@20251001": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.00000125,
    "cacheRead": 1e-7
  },
  "vertex_ai/claude-3-5-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3.0000000000000004e-7
  },
  "vertex_ai/claude-3-5-sonnet@20240620": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3.0000000000000004e-7
  },
  "vertex_ai/claude-3-7-sonnet@20250219": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "vertex_ai/claude-3-haiku": {
    "input": 2.5e-7,
    "output": 0.00000125,
    "cacheCreate": 3.1249999999999997e-7,
    "cacheRead": 2.5e-8
  },
  "vertex_ai/claude-3-haiku@20240307": {
    "input": 2.5e-7,
    "output": 0.00000125,
    "cacheCreate": 3.1249999999999997e-7,
    "cacheRead": 2.5e-8
  },
  "vertex_ai/claude-3-opus": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.000018750000000000002,
    "cacheRead": 0.0000015
  },
  "vertex_ai/claude-3-opus@20240229": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.000018750000000000002,
    "cacheRead": 0.0000015
  },
  "vertex_ai/claude-3-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3.0000000000000004e-7
  },
  "vertex_ai/claude-3-sonnet@20240229": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3.0000000000000004e-7
  },
  "vertex_ai/claude-opus-4": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "vertex_ai/claude-opus-4-1": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "vertex_ai/claude-opus-4-1@20250805": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "vertex_ai/claude-opus-4-5": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "vertex_ai/claude-opus-4-5@20251101": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "vertex_ai/claude-opus-4-6": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "vertex_ai/claude-opus-4-6@default": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "vertex_ai/claude-opus-4-7": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "vertex_ai/claude-opus-4-7@default": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "vertex_ai/claude-fable-5": {
    "input": 0.00001,
    "output": 0.00005,
    "cacheCreate": 0.0000125,
    "cacheRead": 0.000001
  },
  "vertex_ai/claude-fable-5@default": {
    "input": 0.00001,
    "output": 0.00005,
    "cacheCreate": 0.0000125,
    "cacheRead": 0.000001
  },
  "vertex_ai/claude-opus-5": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "vertex_ai/claude-opus-5@default": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "vertex_ai/claude-opus-4-8": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "vertex_ai/claude-opus-4-8@default": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "vertex_ai/claude-sonnet-4-5": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "vertex_ai/claude-sonnet-5": {
    "input": 0.000002,
    "output": 0.00001,
    "cacheCreate": 0.0000025,
    "cacheRead": 2e-7
  },
  "vertex_ai/claude-sonnet-4-6": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "vertex_ai/claude-sonnet-4-5@20250929": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "vertex_ai/claude-opus-4@20250514": {
    "input": 0.000015,
    "output": 0.000075,
    "cacheCreate": 0.00001875,
    "cacheRead": 0.0000015
  },
  "vertex_ai/claude-sonnet-4": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "vertex_ai/claude-sonnet-4@20250514": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7,
    "inputAbove200k": 0.000006,
    "outputAbove200k": 0.0000225,
    "cacheCreateAbove200k": 0.0000075,
    "cacheReadAbove200k": 6e-7
  },
  "vertex_ai/claude-sonnet-5@default": {
    "input": 0.000002,
    "output": 0.00001,
    "cacheCreate": 0.0000025,
    "cacheRead": 2e-7
  },
  "vertex_ai/claude-sonnet-4-6@default": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "bedrock/us-gov-east-1/anthropic.claude-haiku-4-5-20251001-v1:0": {
    "input": 0.0000012,
    "output": 0.000006,
    "cacheCreate": 0.0000015,
    "cacheRead": 1.2e-7
  },
  "bedrock/us-gov-west-1/anthropic.claude-haiku-4-5-20251001-v1:0": {
    "input": 0.0000012,
    "output": 0.000006,
    "cacheCreate": 0.0000015,
    "cacheRead": 1.2e-7
  },
  "snowflake/claude-sonnet-4-5": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "snowflake/claude-sonnet-4-6": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "snowflake/claude-4-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "snowflake/claude-4-opus": {
    "input": 0.000005,
    "output": 0.000025,
    "cacheCreate": 0.00000625,
    "cacheRead": 5e-7
  },
  "snowflake/claude-haiku-4-5": {
    "input": 0.000001,
    "output": 0.000005,
    "cacheCreate": 0.0000012499999999999999,
    "cacheRead": 1e-7
  },
  "snowflake/claude-3-7-sonnet": {
    "input": 0.000003,
    "output": 0.000015,
    "cacheCreate": 0.00000375,
    "cacheRead": 3e-7
  },
  "claude-mythos-5": {
    "input": 0.00001,
    "output": 0.00005,
    "cacheCreate": 0.0000125,
    "cacheRead": 0.000001
  },
  "claude-mythos-preview": {
    "input": 0.00001,
    "output": 0.00005,
    "cacheCreate": 0.0000125,
    "cacheRead": 0.000001
  }
};
