/**
 * Dev-time generator: fetch the LiteLLM pricing table, keep only Anthropic
 * models, normalize each into `ModelPricing`, and emit
 * `src/pricing/embeddedFallback.ts`. Run with `npm run pricing:snapshot`.
 *
 * The emitted snapshot is the offline fallback the statusline uses when the
 * network and the on-disk cache are both unavailable — so it is committed.
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  normalizePricingEntry,
  type PricingTable,
  type RawLiteLLMEntry,
} from '../src/types/Pricing.js';

const LITELLM_URL =
  'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json';

async function main(): Promise<void> {
  const res = await fetch(LITELLM_URL);
  if (!res.ok) {
    throw new Error(`LiteLLM fetch failed: ${res.status} ${res.statusText}`);
  }
  const raw = (await res.json()) as Record<string, RawLiteLLMEntry>;

  const table: PricingTable = {};
  for (const [name, entry] of Object.entries(raw)) {
    if (name === 'sample_spec') {
      continue;
    }
    const isAnthropic =
      entry.litellm_provider === 'anthropic' || name.toLowerCase().includes('claude');
    if (!isAnthropic) {
      continue;
    }
    const pricing = normalizePricingEntry(entry);
    if (pricing) {
      table[name] = pricing;
    }
  }

  const count = Object.keys(table).length;
  if (count === 0) {
    throw new Error('No Anthropic models found in LiteLLM data — aborting.');
  }

  const here = dirname(fileURLToPath(import.meta.url));
  const out = join(here, '..', 'src', 'pricing', 'embeddedFallback.ts');
  const body = `// AUTO-GENERATED by scripts/build-pricing-snapshot.ts — do not edit by hand.
// Offline pricing fallback: Anthropic models only, sourced from LiteLLM.
import type { PricingTable } from '../types/Pricing.js';

export const EMBEDDED_PRICING: PricingTable = ${JSON.stringify(table, null, 2)};
`;
  await writeFile(out, body, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`Wrote ${count} Anthropic models to ${out}`);
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
